# Generated by Django 4.2.2 on 2023-06-25 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d7648e9-2828-477b-936d-49dcc2a7f6ea'), help_text='Unique IF for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
