# Generated by Django 4.2.2 on 2023-06-26 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_author_image_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('593ea423-0804-49eb-bf44-a78a61b0577c'), help_text='Unique IF for this particular book across the whole library', primary_key=True, serialize=False),
        ),
    ]
